### PR TITLE
Admsrules loader

### PR DESCRIPTION
**Pull request by guitorri**
Fix the dynamic loader on OS X.

### CODE REVIEW

**Comment by guitorri** [comment]
I will give it a try on Windows to see if the dynamic loader still works with the shipped Mingw toolchain.
Can you take a look at your side. Yes you might need to make install or copy the files over to the be able to test it.

**Comment by guitorri** [comment]
I don't get why the pattern rules and the suffixes are not working. Need to read once again the make docs.

**Comment by felix-salfelder** [comment]
> I don't get why the pattern rules and the suffixes are not working. Need to read once again the make docs.

i think I did a mistake. in automake you write `SUFFIXES = ...`, this gets translated to `.SUFFIXES: ..`. the former does not have any effect in plain make, but i accidentally used it here.

can you confirm?

**Comment by guitorri** [comment]
Yep. The `.SUFFIXES: ...` seems fine. I did a forced update on the PR.

**Comment by felix-salfelder** [comment]
@guitorri this is converging. thank you

**Pull request merged**
